export const selectors = {
  nav: {
    board: '[data-testid="nav-board"]',
    graph: '[data-testid="nav-graph"]',
    agents: '[data-testid="nav-agents"]',
    settings: '[data-testid="nav-settings"]',
    usage: '[data-testid="nav-usage"]',
  },
  board: {
    title: 'h1:has-text("Agent Board")',
    search: '[data-testid="board-search"]',
    filter: '[data-testid="board-filter"]',
    rescanBtn: 'button[title="Rescan"]',
    newAgentBtn: '[data-testid="board-new-agent-btn"]',
    addAgentBtn: 'button:has-text("Add Agent")',
  },
  modal: {
    createTitle: 'h2:has-text("Create New Agent")',
    nameInput: 'input[placeholder="e.g., code-assistant"]',
    descInput: 'textarea[placeholder="What does this agent do?"]',
    createBtn: 'button:has-text("Create")',
    cancelBtn: 'button:has-text("Cancel")',
    agentTypeBtn: 'button:has-text("Agent")',
    skillTypeBtn: 'button:has-text("Skill")',
  },
  cardDetail: {
    container: '[data-testid="card-detail-modal"]',
    editBtn: 'button:has-text("Edit")',
    deleteBtn: 'button:has-text("Delete")',
    closeBtn: 'button >> svg',
  },
  graph: {
    title: 'h1:has-text("Agent Graph")',
    reactFlow: '.react-flow',
    loading: 'text=Loading graph...',
    controls: '.react-flow__controls',
    minimap: '.react-flow__minimap',
    background: '.react-flow__background',
  },
  agents: {
    title: 'h1:has-text("Agents")',
    search: 'input[placeholder="Search..."]',
    emptyState: 'text=No agents found',
  },
  agentDetail: {
    saveBtn: '[data-testid="agent-detail-save-btn"]',
    deleteBtn: '[data-testid="agent-detail-delete-btn"]',
    editTab: '[data-testid="tab-edit"]',
    filesTab: '[data-testid="tab-files"]',
    previewTab: '[data-testid="tab-preview"]',
    mdEditor: '[data-color-mode="light"]',
  },
  settings: {
    title: 'h1:has-text("Settings")',
    workspaceName: 'section:has-text("Workspace") input',
    saveBtn: '[data-testid="settings-save-btn"]',
    exportBtn: 'button:has-text("Export")',
    rescanBtn: 'button:has-text("Rescan")',
    addPathInput: 'input[placeholder="/path/to/agents"]',
    addPathBtn: '[data-testid="settings-add-path-btn"]',
    addGroupInput: 'input[placeholder="Group name"]',
    addGroupBtn: '[data-testid="settings-add-group-btn"]',
  },
  usage: {
    page: '[data-testid="usage-page"]',
    overview: '[data-testid="usage-overview"]',
    overviewToday: '[data-testid="usage-overview-today"]',
    kline: '[data-testid="usage-kline"]',
    klineChart: '[data-testid="usage-kline-chart"]',
    stats: '[data-testid="usage-stats"]',
    table: '[data-testid="usage-table"]',
    sourceAll: '[data-testid="usage-source-all"]',
    sourceClaude: '[data-testid="usage-source-claude"]',
    range24h: '[data-testid="usage-range-24h"]',
    rescan: '[data-testid="usage-rescan"]',
  },
};
